// Compiler-specific details - GNU C++ 3.2 

#ifndef _UTIL_PLATFORM_COMPILER_GCC32_COMPILER_HPP_
#define _UTIL_PLATFORM_COMPILER_GCC32_COMPILER_HPP_

#endif //! _UTIL_PLATFORM_COMPILER_GCC32_COMPILER_HPP_
